global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - benchmark-prometheus:9090

  - job_name: worker-seckill
    metrics_path: /metrics
    static_configs:
      - targets:
          - benchmark-worker-seckill:9404
