#!/usr/bin/env bash

set -euo pipefail

bucket_count="${1:-${SECKILL_BUCKET_COUNT:-4}}"

if ! [[ "$bucket_count" =~ ^[0-9]+$ ]] || [[ "$bucket_count" -lt 1 ]]; then
  echo "SECKILL bucket count must be a positive integer, got: $bucket_count" >&2
  exit 1
fi

export SECKILL_BUCKET_COUNT="$bucket_count"
export KAFKA_SECKILL_BUCKET_COUNT="${KAFKA_SECKILL_BUCKET_COUNT:-$SECKILL_BUCKET_COUNT}"
export BENCHMARK_SECKILL_BUCKET_COUNT="${BENCHMARK_SECKILL_BUCKET_COUNT:-$SECKILL_BUCKET_COUNT}"
export KAFKA_SECKILL_REQUEST_TOPIC_PARTITIONS="${KAFKA_SECKILL_REQUEST_TOPIC_PARTITIONS:-$SECKILL_BUCKET_COUNT}"
export KAFKA_SECKILL_RESULT_TOPIC_PARTITIONS="${KAFKA_SECKILL_RESULT_TOPIC_PARTITIONS:-$SECKILL_BUCKET_COUNT}"
export KAFKA_SECKILL_DLQ_TOPIC_PARTITIONS="${KAFKA_SECKILL_DLQ_TOPIC_PARTITIONS:-$SECKILL_BUCKET_COUNT}"

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
  cat <<EOF
SECKILL_BUCKET_COUNT=$SECKILL_BUCKET_COUNT
KAFKA_SECKILL_BUCKET_COUNT=$KAFKA_SECKILL_BUCKET_COUNT
BENCHMARK_SECKILL_BUCKET_COUNT=$BENCHMARK_SECKILL_BUCKET_COUNT
KAFKA_SECKILL_REQUEST_TOPIC_PARTITIONS=$KAFKA_SECKILL_REQUEST_TOPIC_PARTITIONS
KAFKA_SECKILL_RESULT_TOPIC_PARTITIONS=$KAFKA_SECKILL_RESULT_TOPIC_PARTITIONS
KAFKA_SECKILL_DLQ_TOPIC_PARTITIONS=$KAFKA_SECKILL_DLQ_TOPIC_PARTITIONS
EOF
fi
