// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CheckoutIntentProjection struct {
	CheckoutIntentID   pgtype.UUID        `json:"checkout_intent_id"`
	AggregateVersion   int64              `json:"aggregate_version"`
	LastEventID        int64              `json:"last_event_id"`
	BuyerID            string             `json:"buyer_id"`
	Status             string             `json:"status"`
	Items              []byte             `json:"items"`
	PaymentID          pgtype.UUID        `json:"payment_id"`
	OrderID            pgtype.UUID        `json:"order_id"`
	RejectionReason    pgtype.Text        `json:"rejection_reason"`
	CancellationReason pgtype.Text        `json:"cancellation_reason"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type CommandStatus struct {
	CommandID        pgtype.UUID        `json:"command_id"`
	CorrelationID    pgtype.UUID        `json:"correlation_id"`
	IdempotencyKey   pgtype.Text        `json:"idempotency_key"`
	Status           string             `json:"status"`
	CheckoutIntentID pgtype.UUID        `json:"checkout_intent_id"`
	EventID          pgtype.UUID        `json:"event_id"`
	IsDuplicate      bool               `json:"is_duplicate"`
	FailureCode      pgtype.Text        `json:"failure_code"`
	FailureMessage   pgtype.Text        `json:"failure_message"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type EventStore struct {
	ID               int64              `json:"id"`
	EventID          pgtype.UUID        `json:"event_id"`
	EventType        string             `json:"event_type"`
	EventVersion     int32              `json:"event_version"`
	AggregateType    string             `json:"aggregate_type"`
	AggregateID      string             `json:"aggregate_id"`
	AggregateVersion int64              `json:"aggregate_version"`
	Payload          []byte             `json:"payload"`
	Metadata         []byte             `json:"metadata"`
	IdempotencyKey   pgtype.Text        `json:"idempotency_key"`
	OccurredAt       pgtype.Timestamptz `json:"occurred_at"`
}

type OrderProjection struct {
	OrderID          pgtype.UUID        `json:"order_id"`
	AggregateVersion int64              `json:"aggregate_version"`
	LastEventID      int64              `json:"last_event_id"`
	CheckoutIntentID pgtype.UUID        `json:"checkout_intent_id"`
	BuyerID          string             `json:"buyer_id"`
	Status           string             `json:"status"`
	PaymentStatus    string             `json:"payment_status"`
	Items            []byte             `json:"items"`
	TotalAmountMinor int64              `json:"total_amount_minor"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Product struct {
	ProductID   string             `json:"product_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ProjectionCheckpoint struct {
	ProjectionName string             `json:"projection_name"`
	LastEventID    int64              `json:"last_event_id"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Sku struct {
	SkuID            string             `json:"sku_id"`
	ProductID        string             `json:"product_id"`
	SkuCode          string             `json:"sku_code"`
	Name             string             `json:"name"`
	PriceAmountMinor int64              `json:"price_amount_minor"`
	Currency         string             `json:"currency"`
	Status           string             `json:"status"`
	Attributes       []byte             `json:"attributes"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type SkuInventoryProjection struct {
	SkuID            string             `json:"sku_id"`
	AggregateVersion int64              `json:"aggregate_version"`
	LastEventID      int64              `json:"last_event_id"`
	OnHand           int32              `json:"on_hand"`
	Reserved         int32              `json:"reserved"`
	Sold             int32              `json:"sold"`
	Available        int32              `json:"available"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type StagingBuyIntentCommand struct {
	StagingID      int64              `json:"staging_id"`
	CommandID      pgtype.UUID        `json:"command_id"`
	CorrelationID  pgtype.UUID        `json:"correlation_id"`
	IdempotencyKey pgtype.Text        `json:"idempotency_key"`
	AggregateType  string             `json:"aggregate_type"`
	AggregateID    string             `json:"aggregate_id"`
	PayloadJson    []byte             `json:"payload_json"`
	MetadataJson   []byte             `json:"metadata_json"`
	IngestStatus   string             `json:"ingest_status"`
	BatchID        pgtype.UUID        `json:"batch_id"`
	RetryCount     int32              `json:"retry_count"`
	ReceivedAt     pgtype.Timestamptz `json:"received_at"`
	ClaimedAt      pgtype.Timestamptz `json:"claimed_at"`
	ProcessedAt    pgtype.Timestamptz `json:"processed_at"`
	LastErrorCode  pgtype.Text        `json:"last_error_code"`
}
