// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimPendingBatch = `-- name: ClaimPendingBatch :many
with next_batch as (
  select staging_id
  from staging_buy_intent_command
  where ingest_status = 'pending'
  order by received_at asc
  limit $2
  for update skip locked
)
update staging_buy_intent_command as staging
set
  ingest_status = 'claimed',
  batch_id = $1,
  claimed_at = now()
from next_batch
where staging.staging_id = next_batch.staging_id
returning
  staging.staging_id,
  staging.command_id,
  staging.correlation_id,
  staging.idempotency_key,
  staging.payload_json
`

type ClaimPendingBatchParams struct {
	BatchID pgtype.UUID `json:"batch_id"`
	Limit   int32       `json:"limit"`
}

type ClaimPendingBatchRow struct {
	StagingID      int64       `json:"staging_id"`
	CommandID      pgtype.UUID `json:"command_id"`
	CorrelationID  pgtype.UUID `json:"correlation_id"`
	IdempotencyKey pgtype.Text `json:"idempotency_key"`
	PayloadJson    []byte      `json:"payload_json"`
}

func (q *Queries) ClaimPendingBatch(ctx context.Context, arg ClaimPendingBatchParams) ([]ClaimPendingBatchRow, error) {
	rows, err := q.db.Query(ctx, claimPendingBatch, arg.BatchID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimPendingBatchRow
	for rows.Next() {
		var i ClaimPendingBatchRow
		if err := rows.Scan(
			&i.StagingID,
			&i.CommandID,
			&i.CorrelationID,
			&i.IdempotencyKey,
			&i.PayloadJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCommandStatus = `-- name: GetCommandStatus :one
select
  command_id,
  correlation_id,
  status,
  checkout_intent_id,
  event_id,
  is_duplicate,
  failure_code,
  failure_message,
  created_at,
  updated_at
from command_status
where command_id = $1
limit 1
`

type GetCommandStatusRow struct {
	CommandID        pgtype.UUID        `json:"command_id"`
	CorrelationID    pgtype.UUID        `json:"correlation_id"`
	Status           string             `json:"status"`
	CheckoutIntentID pgtype.UUID        `json:"checkout_intent_id"`
	EventID          pgtype.UUID        `json:"event_id"`
	IsDuplicate      bool               `json:"is_duplicate"`
	FailureCode      pgtype.Text        `json:"failure_code"`
	FailureMessage   pgtype.Text        `json:"failure_message"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetCommandStatus(ctx context.Context, commandID pgtype.UUID) (GetCommandStatusRow, error) {
	row := q.db.QueryRow(ctx, getCommandStatus, commandID)
	var i GetCommandStatusRow
	err := row.Scan(
		&i.CommandID,
		&i.CorrelationID,
		&i.Status,
		&i.CheckoutIntentID,
		&i.EventID,
		&i.IsDuplicate,
		&i.FailureCode,
		&i.FailureMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventByIdempotencyKey = `-- name: GetEventByIdempotencyKey :one
select
  id,
  event_id,
  event_type,
  event_version,
  aggregate_type,
  aggregate_id,
  aggregate_version,
  payload,
  metadata,
  idempotency_key,
  occurred_at
from event_store
where idempotency_key = $1
limit 1
`

func (q *Queries) GetEventByIdempotencyKey(ctx context.Context, idempotencyKey pgtype.Text) (EventStore, error) {
	row := q.db.QueryRow(ctx, getEventByIdempotencyKey, idempotencyKey)
	var i EventStore
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EventType,
		&i.EventVersion,
		&i.AggregateType,
		&i.AggregateID,
		&i.AggregateVersion,
		&i.Payload,
		&i.Metadata,
		&i.IdempotencyKey,
		&i.OccurredAt,
	)
	return i, err
}

const insertCheckoutIntentCreatedEvent = `-- name: InsertCheckoutIntentCreatedEvent :one
insert into event_store (
  event_id,
  event_type,
  event_version,
  aggregate_type,
  aggregate_id,
  aggregate_version,
  payload,
  metadata,
  idempotency_key,
  occurred_at
)
values ($1, 'CheckoutIntentCreated', 1, 'checkout', $2, 1, $3::jsonb, $4::jsonb, $5, $6)
on conflict (idempotency_key)
  where idempotency_key is not null
  do nothing
returning
  id,
  event_id,
  event_type,
  event_version,
  aggregate_type,
  aggregate_id,
  aggregate_version,
  payload,
  metadata,
  idempotency_key,
  occurred_at
`

type InsertCheckoutIntentCreatedEventParams struct {
	EventID        pgtype.UUID        `json:"event_id"`
	AggregateID    string             `json:"aggregate_id"`
	Column3        []byte             `json:"column_3"`
	Column4        []byte             `json:"column_4"`
	IdempotencyKey pgtype.Text        `json:"idempotency_key"`
	OccurredAt     pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) InsertCheckoutIntentCreatedEvent(ctx context.Context, arg InsertCheckoutIntentCreatedEventParams) (EventStore, error) {
	row := q.db.QueryRow(ctx, insertCheckoutIntentCreatedEvent,
		arg.EventID,
		arg.AggregateID,
		arg.Column3,
		arg.Column4,
		arg.IdempotencyKey,
		arg.OccurredAt,
	)
	var i EventStore
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EventType,
		&i.EventVersion,
		&i.AggregateType,
		&i.AggregateID,
		&i.AggregateVersion,
		&i.Payload,
		&i.Metadata,
		&i.IdempotencyKey,
		&i.OccurredAt,
	)
	return i, err
}

const markCommandCreated = `-- name: MarkCommandCreated :exec
update command_status
set
  status = 'created',
  checkout_intent_id = $2,
  event_id = $3,
  is_duplicate = $4,
  failure_code = null,
  failure_message = null,
  updated_at = now()
where command_id = $1
  and status in ('accepted', 'processing')
`

type MarkCommandCreatedParams struct {
	CommandID        pgtype.UUID `json:"command_id"`
	CheckoutIntentID pgtype.UUID `json:"checkout_intent_id"`
	EventID          pgtype.UUID `json:"event_id"`
	IsDuplicate      bool        `json:"is_duplicate"`
}

func (q *Queries) MarkCommandCreated(ctx context.Context, arg MarkCommandCreatedParams) error {
	_, err := q.db.Exec(ctx, markCommandCreated,
		arg.CommandID,
		arg.CheckoutIntentID,
		arg.EventID,
		arg.IsDuplicate,
	)
	return err
}

const markCommandFailed = `-- name: MarkCommandFailed :exec
update command_status
set
  status = 'failed',
  failure_code = $2,
  failure_message = $3,
  updated_at = now()
where command_id = $1
  and status in ('accepted', 'processing')
`

type MarkCommandFailedParams struct {
	CommandID      pgtype.UUID `json:"command_id"`
	FailureCode    pgtype.Text `json:"failure_code"`
	FailureMessage pgtype.Text `json:"failure_message"`
}

func (q *Queries) MarkCommandFailed(ctx context.Context, arg MarkCommandFailedParams) error {
	_, err := q.db.Exec(ctx, markCommandFailed, arg.CommandID, arg.FailureCode, arg.FailureMessage)
	return err
}

const markCommandProcessing = `-- name: MarkCommandProcessing :exec
update command_status
set
  status = case when status = 'accepted' then 'processing' else status end,
  updated_at = now()
where command_id = $1
  and status in ('accepted', 'processing')
`

func (q *Queries) MarkCommandProcessing(ctx context.Context, commandID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markCommandProcessing, commandID)
	return err
}

const markStagingFailed = `-- name: MarkStagingFailed :exec
update staging_buy_intent_command
set
  ingest_status = $2,
  processed_at = now(),
  last_error_code = $3,
  retry_count = retry_count + 1
where staging_id = $1
`

type MarkStagingFailedParams struct {
	StagingID     int64       `json:"staging_id"`
	IngestStatus  string      `json:"ingest_status"`
	LastErrorCode pgtype.Text `json:"last_error_code"`
}

func (q *Queries) MarkStagingFailed(ctx context.Context, arg MarkStagingFailedParams) error {
	_, err := q.db.Exec(ctx, markStagingFailed, arg.StagingID, arg.IngestStatus, arg.LastErrorCode)
	return err
}

const markStagingMerged = `-- name: MarkStagingMerged :exec
update staging_buy_intent_command
set
  ingest_status = 'merged',
  processed_at = now(),
  last_error_code = null
where staging_id = $1
`

func (q *Queries) MarkStagingMerged(ctx context.Context, stagingID int64) error {
	_, err := q.db.Exec(ctx, markStagingMerged, stagingID)
	return err
}

const touchCommandStatus = `-- name: TouchCommandStatus :exec
update command_status
set updated_at = now()
where command_id = $1
`

func (q *Queries) TouchCommandStatus(ctx context.Context, commandID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchCommandStatus, commandID)
	return err
}
