// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ClaimPendingBatch(ctx context.Context, arg ClaimPendingBatchParams) ([]ClaimPendingBatchRow, error)
	GetCommandStatus(ctx context.Context, commandID pgtype.UUID) (GetCommandStatusRow, error)
	GetEventByIdempotencyKey(ctx context.Context, idempotencyKey pgtype.Text) (EventStore, error)
	InsertCheckoutIntentCreatedEvent(ctx context.Context, arg InsertCheckoutIntentCreatedEventParams) (EventStore, error)
	MarkCommandCreated(ctx context.Context, arg MarkCommandCreatedParams) error
	MarkCommandFailed(ctx context.Context, arg MarkCommandFailedParams) error
	MarkCommandProcessing(ctx context.Context, commandID pgtype.UUID) error
	MarkStagingFailed(ctx context.Context, arg MarkStagingFailedParams) error
	MarkStagingMerged(ctx context.Context, stagingID int64) error
	TouchCommandStatus(ctx context.Context, commandID pgtype.UUID) error
}

var _ Querier = (*Queries)(nil)
